<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\AbstractProduct */
$shippings =  $block->getProduct()->getShippingMe() ? $block->getProduct()->getShippingMe() : "";
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$method = $objectManager->create('Cowell\ProductShippingMethod\Helper\ShippingMethods')
?>
<label for="">
    Shipping Method:
</label>

<div>
    <?= $method->get($shippings) ?>
</div>

<label for="">
    Payment Fee:
</label>
<div>
    <?=  $block->getProduct()->getPaymentFe() ? $block->getProduct()->getPaymentFe() : 0 ?>
</div>
